routes/admin.php
<?php


Route::group(['as' => 'admin.', 'middleware' => 'guest:admin'], function () {

    Route::get('login', 'Auth\AdminLoginController@showLoginForm')
        ->name('login');

    Route::post('login', 'Auth\AdminLoginController@login')
        ->name('login');

});



Route::group(['as' => 'admin.', 'middleware' => 'auth:admin'], function () {

    Route::post('logout', 'Auth\AdminLoginController@logout')
        ->name('logout');

    Route::get('profile/change-password', 'ProfileController@changePasswordView')
        ->name('profile.changePassword');

    Route::post('profile/change-password', 'ProfileController@changePassword')
        ->name('profile.changePassword');

    Route::get('/', 'DashboardController@index')
        ->name('dashboard');

    Route::resource('users', 'UserController');
    Route::post('users/change-status', 'UserController@changeStatus')
        ->name('users.change-status');

    Route::resource('order', 'OrderController');
    Route::post('order/change-status', 'OrderController@changeStatus')
        ->name('order.change-status');

    Route::resource('tickets', 'TicketController');
    Route::resource('pages', 'PageController');


    Route::prefix('settings')->group(function () {

        Route::resource('carriers', 'CarrierSettingsController');

        Route::post('create-language', 'LanguageSettingsController@createLanguage')
            ->name('create-language');
        
    });



});

Route::get('/h', function () {
    return view('Admin.invoice.index');
});

routes/web.php
<?php

// Language Routes
Route::get('lang/{langKey}', function ($langKey) {
    if (array_key_exists($langKey, Config::get('languages'))) {
        Session::put('appLocale', $langKey);
    }
    return redirect()->back();
})->name('changeLanguage');


Route::get('/sess', function () {
    dd(session()->all());
    return session()->all();
});


Route::group(['namespace' => 'StripeCon', 'middleware' => 'verified', 'prefix' => 'stripe'], function () {

    Route::get('get-cards', 'UserStripeController@getCards')
        ->name('user.getCards');

    Route::post('update-card', 'UserStripeController@updateCard')
        ->name('user.updateCard');

    Route::post('get-single-card', 'UserStripeController@getSingleCard')
        ->name('user.getSingleCard');

    Route::get('get-single-customer', 'UserStripeController@getCustomer')
        ->name('user.getSingleCustomer');
});

Route::middleware('guest:admin', function () {

});


Auth::routes(['verify' => true]);


Route::middleware('guest', function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')
        ->name('login');

    Route::get('/register', 'Auth\RegisterController@register')
        ->name('register');


    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
        ->name('password.request');

    Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
        ->name('password.reset');

});




Route::get('/email/verify', 'Auth\VerificationController@show')->name('verification.notice');

Route::group(['namespace' => 'FrontEndCon'], function () {

    // Fedex endpoints for testing purpose
    Route::get('/fedex/get-quotes', 'CarrierController@getQuotes')
        ->name('fedex.getQuotes');

    Route::get('/fedex/create-shipping', 'CarrierController@createShipping')
        ->name('fedex.createShipping');

    Route::get('/fedex/validate-address', 'CarrierController@validateAddress')
        ->name('fedex.validateAddress');




    Route::get('/', 'HomeController@index')
        ->name('root');

    Route::get('/home', 'UserController@home')
        ->name('home');

    Route::resource('ship-comparator', 'ShipComparatorController');

    Route::post('selected-carrier', 'ShipComparatorController@selectedCarrier')
        ->name('selected-carrier');

    Route::resource('ship-details', 'ShipDetailsController');

    Route::post('ship-details/updateCost', 'ShipDetailsController@updateCost')
        ->name('ship-details.updateCost');


    Route::resource('ship-address', 'ShipAddressController');

    Route::resource('payment-design', 'PaymentDesignController');

    Route::resource('invoice', 'InvoiceController');

    Route::resource('order-confirm', 'OrderConfirmController');


    Route::group(['middleware' => 'verified', 'prefix' => 'user'], function () {

        Route::get('/', 'HomeController@index');

        Route::post('/single-update', 'UserController@singleUpdate')
            ->name('profile.singleUpdate');



        // User routes
        Route::group(['as' => 'user.'], function() {
            Route::resource('order', 'UserOrderController');

            Route::resource('address', 'UserAddressController');
            Route::resource('credit-card', 'UserCardController');
            Route::resource('profile', 'UserProfileController');
            Route::resource('fatture', 'UserInvoiceController');

            Route::get('/dashboard', 'UserController@dashboard')
                ->name('dashboard');

            Route::get('/pass-change', 'UserController@passChange')
                ->name('passChange');

            Route::get('/ticket', 'TicketController@ticket')
                ->name('ticket');

            Route::get('/tickets', 'TicketController@getTickets')
                ->name('getTickets');

            Route::get('/single-ticket', 'TicketController@singleTicket')
                ->name('singleTicket');
        });


        Route::get('/email/change/{token}', 'UserController@emailChange')
            ->name('changeEmail.confirm');

        Route::post('/ticket', 'TicketController@cruTicket')
            ->name('cru.ticket');

        Route::post('/reply', 'TicketController@cruReply')
            ->name('cru.reply');

        Route::post('/file-upload', 'TicketController@fileUpload')
            ->name('ticket.fileUpload');
    });
});

Route::group(['prefix' => 'api/v0.1', 'as' => 'api.'], function () {
    Route::resource('ship-details', 'Api\ShipDetailsController');
});


// Custom page route goes here
Route::get('/{slug}', 'HomeController@slug')
    ->name('page.show');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $guarded = ['id'];
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/BackEndCon/ProfileController.php
<?php

namespace App\Http\Controllers\BackEndCon;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    public function changePasswordView()
    {
        return view('Admin.profile.change-password');
    }

    public function changePassword(Request $request)
    {
        $user = auth()->user();
        $validatedData = $request->validate([
            'current_password' => ['required', 'string', 'min:8'],
            'password'         => ['required', 'string', 'min:8', 'confirmed']
        ]);
        if (!Hash::check($validatedData['current_password'], $user->password)) {
            return back()->with('error', 'La password non è corretta.');
        }
        $user->update([
            'password' => Hash::make($request->password),
        ]);
        return back()->with('success', 'La tua password è stata modificata.');
    }
}

resources/views/Admin/profile/change-password.blade.php
@extends('Admin.layouts.app')

@section('custom-css')
@endsection

@section('page-title')
    {{ __('translations.Change Password') }}
@endsection

@push('cssLib')
@endpush

@push('css')
@endpush

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="">{{ __('translations.Dashboard') }}</a></li>
@endsection

@section('content')
    <div class="page-content container-fluid">
        <div class="row">
            <!-- Column -->
            <div class="col-lg-6 col-xlg-6 col-md-6">
                <div class="card">
                    <div class="card-body">
                        <form class="form-horizontal form-material" action="{{ route('admin.profile.changePassword') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label class="col-md-12">{{ __('translations.Old Password') }}</label>
                                <div class="col-md-12">
                                    <input type="password" value="{{ old('current_password') }}" class="form-control form-control-line" name="current_password" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">{{ __('translations.New Password') }}</label>
                                <div class="col-md-12">
                                    <input type="password" value="{{ old('password') }}" class="form-control form-control-line" name="password" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-12">{{ __('translations.Confirm Password') }}</label>
                                <div class="col-md-12">
                                    <input type="password" value="{{ old('password_confirmation') }}" class="form-control form-control-line" name="password_confirmation" required>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-12">
                                    <button class="btn btn-success">{{ __('translations.Update Password') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
@endpush