routes/admin.php
<?php


Route::group(['as' => 'admin.', 'middleware' => 'guest:admin'], function () {

    Route::get('login', 'Auth\AdminLoginController@showLoginForm')
        ->name('login');

    Route::post('login', 'Auth\AdminLoginController@login')
        ->name('login');

});



Route::group(['as' => 'admin.', 'middleware' => 'auth:admin'], function () {

    Route::post('logout', 'Auth\AdminLoginController@logout')
        ->name('logout');

    Route::get('profile/change-password', 'ProfileController@changePasswordView')
        ->name('profile.changePassword');

    Route::post('profile/change-password', 'ProfileController@changePassword')
        ->name('profile.changePassword');

    Route::get('/', 'DashboardController@index')
        ->name('dashboard');

    Route::resource('users', 'UserController');
    Route::post('users/change-status', 'UserController@changeStatus')
        ->name('users.change-status');

    Route::resource('order', 'OrderController');
    Route::post('order/change-status', 'OrderController@changeStatus')
        ->name('order.change-status');

    Route::resource('tickets', 'TicketController');
    Route::resource('pages', 'PageController');


    Route::prefix('settings')->group(function () {

        Route::resource('carriers', 'CarrierSettingsController');

        Route::post('create-language', 'LanguageSettingsController@createLanguage')
            ->name('create-language');
        
    });



});

Route::get('/h', function () {
    return view('Admin.invoice.index');
});

routes/web.php
<?php

// Language Routes
Route::get('lang/{langKey}', function ($langKey) {
    if (array_key_exists($langKey, Config::get('languages'))) {
        Session::put('appLocale', $langKey);
    }
    return redirect()->back();
})->name('changeLanguage');


Route::get('/sess', function () {
    dd(session()->all());
    return session()->all();
});


Route::group(['namespace' => 'StripeCon', 'middleware' => 'verified', 'prefix' => 'stripe'], function () {

    Route::get('get-cards', 'UserStripeController@getCards')
        ->name('user.getCards');

    Route::post('update-card', 'UserStripeController@updateCard')
        ->name('user.updateCard');

    Route::post('get-single-card', 'UserStripeController@getSingleCard')
        ->name('user.getSingleCard');

    Route::get('get-single-customer', 'UserStripeController@getCustomer')
        ->name('user.getSingleCustomer');
});

Route::middleware('guest:admin', function () {

});


Auth::routes(['verify' => true]);


Route::middleware('guest', function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')
        ->name('login');

    Route::get('/register', 'Auth\RegisterController@register')
        ->name('register');


    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
        ->name('password.request');

    Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
        ->name('password.reset');

});




Route::get('/email/verify', 'Auth\VerificationController@show')->name('verification.notice');

Route::group(['namespace' => 'FrontEndCon'], function () {

    // Fedex endpoints for testing purpose
    Route::get('/fedex/get-quotes', 'CarrierController@getQuotes')
        ->name('fedex.getQuotes');

    Route::get('/fedex/create-shipping', 'CarrierController@createShipping')
        ->name('fedex.createShipping');

    Route::get('/fedex/validate-address', 'CarrierController@validateAddress')
        ->name('fedex.validateAddress');




    Route::get('/', 'HomeController@index')
        ->name('root');

    Route::get('/home', 'UserController@home')
        ->name('home');

    Route::resource('ship-comparator', 'ShipComparatorController');

    Route::post('selected-carrier', 'ShipComparatorController@selectedCarrier')
        ->name('selected-carrier');

    Route::resource('ship-details', 'ShipDetailsController');

    Route::post('ship-details/updateCost', 'ShipDetailsController@updateCost')
        ->name('ship-details.updateCost');


    Route::resource('ship-address', 'ShipAddressController');

    Route::resource('payment-design', 'PaymentDesignController');

    Route::resource('invoice', 'InvoiceController');

    Route::resource('order-confirm', 'OrderConfirmController');


    Route::group(['middleware' => 'verified', 'prefix' => 'user'], function () {

        Route::get('/', 'HomeController@index');

        Route::post('/single-update', 'UserController@singleUpdate')
            ->name('profile.singleUpdate');



        // User routes
        Route::group(['as' => 'user.'], function() {
            Route::resource('order', 'UserOrderController');

            Route::resource('address', 'UserAddressController');
            Route::resource('credit-card', 'UserCardController');
            Route::resource('profile', 'UserProfileController');
            Route::resource('fatture', 'UserInvoiceController');

            Route::get('/dashboard', 'UserController@dashboard')
                ->name('dashboard');

            Route::get('/pass-change', 'UserController@passChange')
                ->name('passChange');

            Route::get('/ticket', 'TicketController@ticket')
                ->name('ticket');

            Route::get('/tickets', 'TicketController@getTickets')
                ->name('getTickets');

            Route::get('/single-ticket', 'TicketController@singleTicket')
                ->name('singleTicket');
        });


        Route::get('/email/change/{token}', 'UserController@emailChange')
            ->name('changeEmail.confirm');

        Route::post('/ticket', 'TicketController@cruTicket')
            ->name('cru.ticket');

        Route::post('/reply', 'TicketController@cruReply')
            ->name('cru.reply');

        Route::post('/file-upload', 'TicketController@fileUpload')
            ->name('ticket.fileUpload');
    });
});

Route::group(['prefix' => 'api/v0.1', 'as' => 'api.'], function () {
    Route::resource('ship-details', 'Api\ShipDetailsController');
});


// Custom page route goes here
Route::get('/{slug}', 'HomeController@slug')
    ->name('page.show');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $guarded = ['id'];
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/BackEndCon/ProfileController.php
<?php

namespace App\Http\Controllers\BackEndCon;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    public function changePasswordView()
    {
        return view('Admin.profile.change-password');
    }

    public function changePassword(Request $request)
    {
        $user = auth()->user();
        $validatedData = $request->validate([
            'current_password' => ['required', 'string', 'min:8'],
            'password'         => ['required', 'string', 'min:8', 'confirmed']
        ]);
        if (!Hash::check($validatedData['current_password'], $user->password)) {
            return back()->with('error', 'La password non è corretta.');
        }
        $user->update([
            'password' => Hash::make($request->password),
        ]);
        return back()->with('success', 'La tua password è stata modificata.');
    }
}

resources/views/User/profile/pages/creditCard.blade.php
@extends('User.profile.profileMaster')

@section('userContent')
    <div id="creditCardVue">
        <div class="state-credit">
            <div class="row">
                <div class="col-md-3 col-sm-6 col-xs-12" v-for="card in cards">
                    <div class="address-box-wrapper">
                        <div class="address-box">
                            <div class="credit-info">
                                <div class="sec-logo">
                                    <i class="mdi mdi-lg  mdi-credit-card"></i>
                                </div>
                                <div class="sec-number"><span>**** **** **** @{{ card.last4 }}</span></div>
                            </div>
                            <div class="add-text">{{ __('translations.Intestata a') }}:</div>
                            <div class="add-text">{{ auth()->user()->first_name .' '. auth()->user()->last_name }}</div>
                            <div data-toggle="modal" data-target="#editCreditCard" class="text-right c-pointer"><span
                                    class="text-green text-sm " @click="getSingleCard(card.id)">{{ __('translations.Modifica') }}</span> &nbsp;<i
                                    class="text-green mdi-sm  mdi mdi-wrench"></i></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- /.modal-edit-credit -->
        <div class="modal fade" id="editCreditCard" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header modal-header-custom">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h5 class="modal-title"><strong>{{ __('translations.Modifica Carta di pagamento') }}</strong></h5>
                    </div>
                    <div class="modal-body modal-header-custom">
                        <p>Utilizza questo form per modificare la carta di credito, ricordati di cliccare sul botte
                            "Salva"
                            al termine. Verrà effettuata addebitata una piccola somma per verifica, la quale verrà
                            immediatamente stornata ad esito positivo.</p>
                        <div class="form-group position-relative margin-btm-input-lg">
                            <div class="mb-1">
                                <label for="">{{ __('translations.Numero carta di credito') }}</label>
                                <input type="text" class="form-control input-gray profile-input"
                                       placeholder="0000 0000 0000 0000"
                                       v-model="updateCard.last4">
                                <img class="input-img" src="{{asset('images/home-img/cards.png')}}" alt="">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group margin-btm-input-lg">
                                    <div class="mb-1">
                                        <label for="">{{ __('translations.Data di scadenza') }}</label>
                                        <input type="text" class="form-control input-gray profile-input"
                                               placeholder="00 / 00"
                                               v-model="updateCard.card_exp">
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group margin-btm-input-lg">
                                    <div class="mb-1">
                                        <label for="">CVV</label>
                                        <input type="text" class="form-control input-gray profile-input"
                                               placeholder="000">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer modal-footer-custom">
                        <button type="button" class="btn btn-close" data-dismiss="modal">{{ __('translations.Non salvare') }}</button>
                        <button class="btn btn-success" @click="updateCardInfo(updateCard.id)" data-dismiss="modal">{{ __('translations.Salva modifiche') }}</button>
                    </div>
                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div><!-- /.modal -->
    </div>
@endsection


@push('scripts')

    <script type="text/javascript">
        new Vue({
            el: '#creditCardVue',
            data: {
                cards: [],
                singleCard: {},
                updateCard: {
                    card_exp: null,
                    last4: null,
                },
            },
            methods: {
                clear() {
                },
                getCards() {
                    let self = this;
                    axios.get("{{route('user.getCards')}}")
                        .then(function (response) {
                            if (!response.data.success) return;
                            self.cards = response.data.cards.data;
                        })
                },
                getSingleCard(cardId) {
                    let self = this;
                    axios.post("{{route('user.getSingleCard')}}", {
                        cardId: cardId
                    }).then(function (response) {
                        console.log(response);
                        if (!response.data.success) return;
                        self.singleCard = response.data.card;
                        self.updateCard.id = self.singleCard.id;
                        self.updateCard.card_exp = self.singleCard.exp_month + '/' + self.singleCard.exp_year;
                        self.updateCard.last4 = '**** **** **** ' + self.singleCard.last4;
                    })
                },
                updateCardInfo(cardId) {
                    let self = this;
                    axios.post("{{route('user.updateCard')}}", {
                        cardId: cardId,
                        card_exp: self.updateCard.card_exp,
                    }).then(function (response) {
                        console.log(response);
                        if (!response.data.success) return;
                        self.singleCard = response.data.card;
                    })
                }
            },
            mounted() {
                this.clear();
                this.getCards();
            },
        });
    </script>
@endpush

resources/views/User/profile/pages/dashboard.blade.php
@extends('User.profile.profileMaster')

@section('userContent')

@endsection


@push('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        console.log('dashboard')
    });
</script>
@endpush

resources/views/User/profile/pages/fatture.blade.php
@extends('User.profile.profileMaster')

@section('userContent')
    <div id="fattureVue">
        <div class="state-order">
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-theme">
                        <thead>
                        <tr>
                            <th>{{ __('translations.Ordine numero') }}</th>
                            <th>{{ __('translations.Data') }}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($invoices as $invoice)
                            <tr>
                                <td>#{{ $invoice->order->order_code }}</td>
                                <td class="text-ash">{{ $invoice->created_at->diffForHumans() }}</td>
                                <td class="text-right">
                                    <form action="{{ route('user.fatture.store') }}" method="POST">
                                        @csrf
                                        <input type="hidden" name="docId" value="{{ $invoice->docId }}">
                                        <button class="mdi btn-transparent btn mdi-md mdi-download"></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection


@push('scripts')

    <script type="text/javascript">
        new Vue({
            el: '#fattureVue',
            data: {},
            methods: {
                clear() {
                }
            },
            mounted() {
                this.clear();
            },
        });
    </script>
@endpush

resources/views/User/profile/pages/order.blade.php
@extends('User.profile.profileMaster')

@section('userContent')
    <div id="orderVue">
        <template v-if="activity=='list'">
            <div class="state-order">
                <div class="row">
                    <div class="col-md-8">
                        <table class="table table-theme">
                            <thead>
                            <tr>
                                <th>Ordine numero</th>
                                <th>Data</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr v-for="order in orders">
                                <td>#@{{ order.order_code }}</td>
                                <td class="text-ash">@{{moment(order.created_at).startOf('hour').fromNow()}}</td>
                                <td class="text-right"><i @click="getSingleOrder(order.id)"
                                                          class="text-ash mdi mdi-dots-horizontal"></i></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-offset-1 col-md-3">
                        <div class="order-box"></div>
                    </div>
                </div>
            </div>
        </template>
        <template v-if="activity=='single'">
            <div class="state-order">
                <div class="row mb-10">
                    <div class="margin-30"></div>
                    <div class="margin-30"></div>
                    <div class="col-sm-4">
                        <div class="text-20">{{ __('translations.Ordine numero') }} #@{{ order_details.order_code }} del @{{moment(order_details.created_at).format('DD/MM/YYYY')}}</div>
                        <div class="margin-15"></div>
                        <div class="order-detail-box text-20">
                            <div class="text-20"><strong>{{ __('translations.Consegna a') }}:</strong></div>
                            <div class="text-20">{{ __('translations.Indirizzo') }}: @{{ order_details.receiver_address_1 + ' ' +
                                order_details.receiver_address_2 }}
                            </div>
                            <div class="margin-30"></div>
                            <div>{{ __('translations.Destinatario') }}: @{{ order_details.receiver_full_name }}</div>
                            <div>{{ __('translations.Email') }}: @{{ order_details.receiver_email }}</div>
                            <div>{{ __('translations.Tel') }}: @{{ order_details.receiver_phone }}</div>
                        </div>
                    </div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-4">
                        <div class="text-right">
                            <small><span>{{ __('translations.Hai bisogno di aiuto?') }}</span>&nbsp; <a href="#" class="text-green">Apri un
                                    ticket</a></small>
                        </div>
                        <div class="text-20">
                            <div class="margin-15"></div>
                            <div><strong>{{ __('translations.Partito da') }}:</strong></div>
                            <div>Indirizzo: @{{ order_details.departure_address_1 + ' ' +
                                order_details.departure_address_2 }}
                            </div>
                            <div class="margin-15"></div>
                            <div>{{ __('translations.Mittente') }}: @{{ order_details.sender_full_name }}</div>
                            <div>{{ __('translations.Email') }}: @{{ order_details.sender_email }}</div>
                            <div>{{ __('translations.Tel') }}: @{{ order_details.departure_phone }}</div>
                            <div class="margin-15"></div>
                            <div><strong>Fattura a:</strong></div>
                            <div>{{ __('translations.Simone Chinaglia') }}</div>
                            <div>p.iva 01382017038</div>
                            <div>SDI: @{{ order_details.sender_sdi_code }}</div>
                            <div>Indirizzo: @{{ order_details.sender_address_1 + ' ' + order_details.sender_address_2
                                }}
                            </div>
                            <div>@{{ order_details.departure_country }}</div>
                            <div class="margin-15"></div>
                            <small><a href="#" class="text-green text-xs">{{ __('translations.Vai alla fattura elettronica') }}</a></small>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="progress-box text-green" :class="(order_details.status===0) ? 'text-orange' : ''">
                            <div class="icon-box">
                                <i class="mdi mdi-flag"></i>
                                <div class="bar-long"></div>
                            </div>
                            <div class="status-box">{{ __('translations.Prenotazione spedizione reicevuta') }}</div>
                        </div>
                        <div class="progress-box" :class="(order_details.status<1) ? 'text-ash' : (order_details.status===1) ? 'text-orange' : 'text-green'">
                            <div class="icon-box">
                                <i class="mdi mdi-calendar-check"></i>
                                <div class="bar-long"></div>
                            </div>
                            <div class="status-box">{{ __('translations.Ritirato presso il cliente') }}</div>
                        </div>
                        <div class="progress-box" :class="(order_details.status<2) ? 'text-ash' : (order_details.status===2) ? 'text-orange' : 'text-green'">
                            <div class="icon-box">
                                <i class="mdi mdi-bus"></i>
                                <div class="bar-long"></div>
                            </div>
                            <div class="status-box">{{ __('translations.In transito') }}</div>
                        </div>
                        <div class="progress-box" :class="(order_details.status<3) ? 'text-ash' : (order_details.status===3) ? 'text-orange' : 'text-green'">
                            <div class="icon-box">
                                <i class="mdi mdi-flag"></i>
                                <div class="bar-long"></div>
                            </div>
                            <div class="status-box">{{ __('translations.Tentativo di consegna 1') }}</div>
                        </div>
                        <div class="progress-box" :class="(order_details.status<4) ? 'text-ash' : (order_details.status===4) ? 'text-orange' : 'text-green'">
                            <div class="icon-box">
                                <i class="mdi mdi-flag"></i>
                                <div class="bar-long"></div>
                            </div>
                            <div class="status-box">{{ __('translations.Tentativo di consegna 2') }}</div>
                        </div>
                        <div class="progress-box" :class="(order_details.status<5) ? 'text-ash' : (order_details.status===5) ? 'text-orange' : 'text-green'">
                            <div class="icon-box">
                                <i class="mdi mdi-flag"></i>
                                <div class="bar-long"></div>
                            </div>
                            <div class="status-box">{{ __('translations.Consegnato all\'ufficio postale di zona') }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </template>
    </div>
@endsection


@push('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment-with-locales.min.js"></script>

    <script type="text/javascript">
        new Vue({
            el: '#orderVue',
            data: {
                activity: 'list',
                orders: [],
                order_details: {},
            },
            methods: {
                moment(time) {
                    return moment(time).locale("it");
                },
                activityChange(activity = 'list') {
                    this.$set(this, 'activity', activity);
                    switch (activity) {
                        case 'single':
                            break;
                        case 'list':
                            this.activity = activity;
                            break;
                        default:
                            this.activity = 'list';
                            break;
                    }
                },
                getAllOrders() {
                    let self = this;
                    axios.get("{{route('api.order.index')}}")
                        .then(function (response) {
                            if (!response.data.success) return;
                            self.orders = response.data.orders;
                        })
                },
                getSingleOrder(order_id) {
                    let self = this;
                    self.activityChange('single');
                    axios.get("{{route('api.order.index')}}/" + order_id)
                        .then(function (response) {
                            if (!response.data.success) return;
                            console.log(response.data.order);
                            self.order_details = response.data.order;
                        })
                }
            },
            mounted() {
                this.getAllOrders();
            },
        });
    </script>
@endpush