routes/admin.php
<?php


Route::group(['as' => 'admin.', 'middleware' => 'guest:admin'], function () {

    Route::get('login', 'Auth\AdminLoginController@showLoginForm')
        ->name('login');

    Route::post('login', 'Auth\AdminLoginController@login')
        ->name('login');

});



Route::group(['as' => 'admin.', 'middleware' => 'auth:admin'], function () {

    Route::post('logout', 'Auth\AdminLoginController@logout')
        ->name('logout');

    Route::get('profile/change-password', 'ProfileController@changePasswordView')
        ->name('profile.changePassword');

    Route::post('profile/change-password', 'ProfileController@changePassword')
        ->name('profile.changePassword');

    Route::get('/', 'DashboardController@index')
        ->name('dashboard');

    Route::resource('users', 'UserController');
    Route::post('users/change-status', 'UserController@changeStatus')
        ->name('users.change-status');

    Route::resource('order', 'OrderController');
    Route::post('order/change-status', 'OrderController@changeStatus')
        ->name('order.change-status');

    Route::resource('tickets', 'TicketController');
    Route::resource('pages', 'PageController');


    Route::prefix('settings')->group(function () {

        Route::resource('carriers', 'CarrierSettingsController');

        Route::post('create-language', 'LanguageSettingsController@createLanguage')
            ->name('create-language');
        
    });



});

Route::get('/h', function () {
    return view('Admin.invoice.index');
});

routes/web.php
<?php

// Language Routes
Route::get('lang/{langKey}', function ($langKey) {
    if (array_key_exists($langKey, Config::get('languages'))) {
        Session::put('appLocale', $langKey);
    }
    return redirect()->back();
})->name('changeLanguage');


Route::get('/sess', function () {
    dd(session()->all());
    return session()->all();
});


Route::group(['namespace' => 'StripeCon', 'middleware' => 'verified', 'prefix' => 'stripe'], function () {

    Route::get('get-cards', 'UserStripeController@getCards')
        ->name('user.getCards');

    Route::post('update-card', 'UserStripeController@updateCard')
        ->name('user.updateCard');

    Route::post('get-single-card', 'UserStripeController@getSingleCard')
        ->name('user.getSingleCard');

    Route::get('get-single-customer', 'UserStripeController@getCustomer')
        ->name('user.getSingleCustomer');
});

Route::middleware('guest:admin', function () {

});


Auth::routes(['verify' => true]);


Route::middleware('guest', function () {

    Route::get('/login', 'Auth\LoginController@showLoginForm')
        ->name('login');

    Route::get('/register', 'Auth\RegisterController@register')
        ->name('register');


    Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')
        ->name('password.request');

    Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')
        ->name('password.reset');

});




Route::get('/email/verify', 'Auth\VerificationController@show')->name('verification.notice');

Route::group(['namespace' => 'FrontEndCon'], function () {

    // Fedex endpoints for testing purpose
    Route::get('/fedex/get-quotes', 'CarrierController@getQuotes')
        ->name('fedex.getQuotes');

    Route::get('/fedex/create-shipping', 'CarrierController@createShipping')
        ->name('fedex.createShipping');

    Route::get('/fedex/validate-address', 'CarrierController@validateAddress')
        ->name('fedex.validateAddress');




    Route::get('/', 'HomeController@index')
        ->name('root');

    Route::get('/home', 'UserController@home')
        ->name('home');

    Route::resource('ship-comparator', 'ShipComparatorController');

    Route::post('selected-carrier', 'ShipComparatorController@selectedCarrier')
        ->name('selected-carrier');

    Route::resource('ship-details', 'ShipDetailsController');

    Route::post('ship-details/updateCost', 'ShipDetailsController@updateCost')
        ->name('ship-details.updateCost');


    Route::resource('ship-address', 'ShipAddressController');

    Route::resource('payment-design', 'PaymentDesignController');

    Route::resource('invoice', 'InvoiceController');

    Route::resource('order-confirm', 'OrderConfirmController');


    Route::group(['middleware' => 'verified', 'prefix' => 'user'], function () {

        Route::get('/', 'HomeController@index');

        Route::post('/single-update', 'UserController@singleUpdate')
            ->name('profile.singleUpdate');



        // User routes
        Route::group(['as' => 'user.'], function() {
            Route::resource('order', 'UserOrderController');

            Route::resource('address', 'UserAddressController');
            Route::resource('credit-card', 'UserCardController');
            Route::resource('profile', 'UserProfileController');
            Route::resource('fatture', 'UserInvoiceController');

            Route::get('/dashboard', 'UserController@dashboard')
                ->name('dashboard');

            Route::get('/pass-change', 'UserController@passChange')
                ->name('passChange');

            Route::get('/ticket', 'TicketController@ticket')
                ->name('ticket');

            Route::get('/tickets', 'TicketController@getTickets')
                ->name('getTickets');

            Route::get('/single-ticket', 'TicketController@singleTicket')
                ->name('singleTicket');
        });


        Route::get('/email/change/{token}', 'UserController@emailChange')
            ->name('changeEmail.confirm');

        Route::post('/ticket', 'TicketController@cruTicket')
            ->name('cru.ticket');

        Route::post('/reply', 'TicketController@cruReply')
            ->name('cru.reply');

        Route::post('/file-upload', 'TicketController@fileUpload')
            ->name('ticket.fileUpload');
    });
});

Route::group(['prefix' => 'api/v0.1', 'as' => 'api.'], function () {
    Route::resource('ship-details', 'Api\ShipDetailsController');
});


// Custom page route goes here
Route::get('/{slug}', 'HomeController@slug')
    ->name('page.show');

resources/views/Admin/pages/action.blade.php
<a class="btn waves-effect waves-light btn-rounded btn-xs btn-success" href="{{ route('admin.pages.edit', $id) }}"><i
        class="fa fa-edit"></i></a>
<button class="btn waves-effect waves-light btn-rounded btn-xs btn-danger" onclick="Delete('{{$id}}')"><i
        class="fa fa-trash"></i></button>

resources/views/Admin/pages/from.blade.php
@extends('Admin.layouts.app')

@section('custom-css')
@endsection

@section('page-title')
    @if (isset($page->id))
        {{ __('translations.Edit Pages') }}
    @else
        {{ __('translations.Create Page') }}
    @endif
@endsection

@push('cssLib')
@endpush

@push('css')
    <link rel="stylesheet" href="{{asset('/template/assets/libs/summernote/dist/summernote-bs4.css')}}">
@endpush

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="">{{ __('translations.Dashboard') }}</a></li>
@endsection

@section('content')
    <div class="page-content container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        @if (isset($page->id))
                            <h4 class="card-title">{{ __('translations.Edit Page') }}</h4>
                        @else
                            <h4 class="card-title">{{ __('translations.Create Page') }}</h4>
                        @endif
                        <h6 class="card-subtitle"></h6>
                        <form
                            @if (isset($page->id))
                            action="{{ route('admin.pages.update', $page->id) }}"
                            @else
                            action="{{ route('admin.pages.store') }}"
                            @endif
                            method="post">
                            @csrf
                            @if (isset($page->id))
                                @method('PUT')
                            @endif
                            <div class="form-group">
                                <label for="page_title">{{ __('translations.Page Title') }}</label>
                                <input type="text" class="form-control" name="page_title" id="page_title"
                                       value="{{ old('page_title', $page->page_title) }}"
                                       placeholder="Page Title">
                            </div>
                            <div class="form-group">
                                <label for="slug">{{ __('translations.Page Slug') }}</label>
                                <input type="text" class="form-control" name="slug" id="slug"
                                       value="{{ old('page_title', $page->slug) }}"
                                       placeholder="Page Slug">
                            </div>
                            <div class="form-group">
                                <label for="meta_title">{{ __('translations.Meta Title') }}</label>
                                <input type="text" class="form-control" name="meta_title" id="meta_title"
                                       value="{{ old('meta_title', $page->meta_title) }}"
                                       placeholder="Meta Title">
                            </div>
                            <div class="form-group">
                                <label for="meta_title">{{ __('translations.Meta Description') }}</label>
                                <textarea class="form-control" name="meta_description" id="meta_description"
                                          cols="30"
                                          rows="10">{{ old('meta_description', $page->meta_description) }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="title">{{ __('translations.Page Content') }}</label>
                                <textarea class="summernote"
                                          name="content">{!! old('content', $page->content) !!}</textarea>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn waves-effect waves-light btn-primary">
                                    {{ __('translations.Save') }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{asset('/template/assets/libs/summernote/dist/summernote-bs4.min.js')}}"></script>
    <script !src="">
        $(document).ready(function () {
            $('.summernote').summernote({
                height: 500
            });
        });
    </script>
@endpush

resources/views/Admin/pages/index.blade.php
@extends('Admin.layouts.app')

@section('custom-css')
@endsection

@section('page-title')
    {{ __('translations.Pages') }}
@endsection

@push('cssLib')
    <link rel="stylesheet"
          href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet"
          href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css">
@endpush

@push('css')
@endpush

@section('breadcrumb')
    <li class="breadcrumb-item"><a href="">{{ __('translations.Dashboard') }}</a></li>
@endsection

@section('content')
    <div class="page-content container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="material-card card">
                    <div class="card-body">
                        <h4 class="card-title">{{ __('translations.Custom Pages List') }}</h4>
                        <h6 class="card-subtitle"></h6>
                        <a href="{{ route('admin.pages.create') }}" class="btn btn-primary float-right mb-3">{{ __('translations.Add New Page') }}</a>
                        <div class="table-responsive">
                            {!! $dataTable->table(['class' => 'table table-striped border display', 'style' => 'width: 100%;'],  true) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.bootstrap4.min.js"></script>

    <script src="{{ asset('vendor/datatables/buttons.server-side.js') }}" type="text/javascript"></script>
    {!! $dataTable->scripts() !!}

    <script type="text/javascript">
        function Delete(id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    axios.delete('{{url()->current()}}/' + id, {}).then(function (response) {
                        if (response.data.success) {
                            $('#tr-' + id).fadeOut();
                            Swal.fire(
                                'Deleted!',
                                'Your order has been deleted.',
                                'success'
                            )
                        }
                    }).catch(function (error) {
                        console.log(error);
                    });
                }
            });
        }
    </script>
@endpush